### ISSUE TITLE
微信登录时微信信息获取该怎么请求?

### ISSUE THREAD

**Issue by yzc90912** [BakerJQ/RxRetroHttp#2]
@GET("userinfo")
    Observable<WeChatInfo> getWeChat(@Query("access_token") String access_token,
                                     @Query("openid") String openid);

    @GET("oauth2/access_token")
    Observable<WeChatToken> getAccessToken(@Query("appid") String appid,
                                           @Query("secret") String secret,
                                           @Query("code") String code,
                                           @Query("grant_type") String grant_type);
请求失败了

**Comment by yzc90912** [comment]
我把微信的地址放在最上边就成功了
RxRetroHttp.init(this)
                .setBaseUrl("https://api.weixin.qq.com/sns/")//other url
                .setDefaultErrMsg("微信信息获取失败")
                .generateRetroClient("wechat")


                .setApiResultClass(MyApiResult.class)
                .setBaseUrl(BaseUrl)
                .setDefaultErrMsg("服务器开小差了")
                .generateRetroClient()

                .setBaseUrl(URL+"/")//other url
                .setDefaultErrMsg("支付失败")
                .generateRetroClient("pay");

下面这个样子失败了
RxRetroHttp.init(this)
                .setApiResultClass(MyApiResult.class)
                .setBaseUrl(BaseUrl)
//                .setDefaultErrMsg("服务器开小差了")
                .generateRetroClient()

                .setBaseUrl(URL+"/")//other url
                .setDefaultErrMsg("支付失败")
                .generateRetroClient("pay")

                .setBaseUrl("https://api.weixin.qq.com/sns/")//other url
                .setDefaultErrMsg("微信信息获取失败")
                .generateRetroClient("wechat")
                .addClient(new SimpleRetroClient(), "wechat");/

**Comment by BakerJQ** [comment]
下面那种情况，apiResultClass并未清除，所以解析的时候继续按照MyApiResult.class的方式去解析了
